### PR TITLE
Using class-based PHPUnit namespace

### PR DESCRIPTION
**Pull request by peter279k**
# Changed log
- Using the class-based PHPUnit namespace to be compatible with latest PHPUnit version.

### CODE REVIEW

**Comment by peter279k** [comment]
It seems that the Circle CI builds are failed during `sudo apt-get install` command.

I think we should modify the Circle CI config for `php` tests.

**Comment by eli-darkly** [comment]
> It seems that the Circle CI builds are failed during sudo apt-get install command. I think we should modify the Circle CI config for php tests.

That's not quite right. The PHP 5.5 job, specifically, failed on an apt-get; I don't see any possible relation to your changes there, so I'm assuming that was a transient problem. The other jobs failed because `composer.lock` does not match `composer.json`:

```
composer validate
./composer.json is valid
The lock file is not up to date with the latest changes in composer.json, it is recommended that you run `composer update`.
```

**Comment by peter279k** [comment]
Hi @eli-darkly, thank you for your reply. I appreciate your help and comment.

I replace the `composer install` with `composer update` command. And I hope the CI build works will be worked successfully :).

**Comment by eli-darkly** [comment]
I'm not sure what the purpose was of your changes to the CircleCI configuration. We had it set up to work as follows: 1. test with the _exact_ dependency versions that were checked in, 2. test after doing `composer update` to the highest compatible versions, and 3. test after doing `composer update` to the _lowest_ compatible versions. You've made it so that it cannot do the first step. I would have thought all that was required was to check in the changes to `composer.lock` that had resulted from your changes to `composer.json`.

**Comment by peter279k** [comment]
Hi @eli-darkly, thank you for your reply.

I've removed the `composer install` command and only using the `composer update && composer validate` to update the dependencies and validate the dependencies.

I think the `composer install` command is duplicated and unused.

**Comment by eli-darkly** [comment]
This is obsolete due to test code reorganization we've been doing for the 4.0 release.

**Pull request closed without merging**
